# Generated by Django 5.0.1 on 2024-01-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Supplier"
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "contact_person",
                    models.CharField(
                        default=None, max_length=100, verbose_name="Contact Person"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        default=None, max_length=70, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(default=None, max_length=20, verbose_name="Phone"),
                ),
            ],
            options={
                "verbose_name": "supplier",
                "verbose_name_plural": "suppliers",
                "ordering": ["supplier"],
            },
        ),
    ]
