# Generated by Django 5.0.1 on 2024-01-24 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("material", "0002_supplier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "material_number",
                    models.CharField(
                        default=None,
                        max_length=15,
                        unique=True,
                        verbose_name="Material Number",
                    ),
                ),
                (
                    "material_id",
                    models.CharField(
                        default=None,
                        max_length=15,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Material ID",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="material.group"
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="material.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "material",
                "verbose_name_plural": "materials",
                "ordering": ["name"],
            },
        ),
    ]
